spring:
  mail:
    host: smtp.163.com
    username: m18370805327@163.com
    password: wxx19981998
  datasource:
    primary:
        driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hy_um?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8
    username: root
    password: SA123
mybatis-plus:
  type-aliases-package: com.athys.springboothysum.entity
  mapper-locations: classpath:/mapper/**.xml
logging:
  level: debug
  file:
    name: springboot-hysum/logs/log/log



